"""initial

Revision ID: 5bfd7cc1e90d
Revises: 
Create Date: 2026-10-03 20:59:47.278339
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5bfd7cc1e90d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('demo_phone', sa.String(length=30), nullable=False),
    sa.Column('language', sa.String(length=30), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendors',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('sku', sa.String(length=40), nullable=False),
    sa.Column('vendor_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('colour', sa.String(length=60), nullable=True),
    sa.Column('fabric', sa.String(length=60), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('inventory', sa.JSON(), nullable=False),
    sa.Column('raw_attributes', sa.JSON(), nullable=False),
    sa.Column('field_provenance', sa.JSON(), nullable=False),
    sa.Column('images', sa.JSON(), nullable=False),
    sa.Column('workflow', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('target_drop', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('orders',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('customer_id', sa.String(length=40), nullable=False),
    sa.Column('product_id', sa.String(length=40), nullable=False),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payment_mode', sa.String(length=20), nullable=False),
    sa.Column('payment_status', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('status_history', sa.JSON(), nullable=False),
    sa.Column('line_items', sa.JSON(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('inspection_status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('event_id', sa.String(length=70), nullable=False),
    sa.Column('customer_id', sa.String(length=40), nullable=False),
    sa.Column('order_id', sa.String(length=40), nullable=True),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=30), nullable=False),
    sa.Column('expected_intent', sa.String(length=30), nullable=False),
    sa.Column('scenario', sa.String(length=60), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_table('review_investigations',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.String(length=40), nullable=False),
    sa.Column('issue_code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('owner', sa.String(length=80), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('product_id', sa.String(length=40), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=30), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('analysis', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runs',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('ticket_id', sa.String(length=40), nullable=False),
    sa.Column('session_id', sa.String(length=80), nullable=False),
    sa.Column('intent', sa.String(length=30), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('proposed_reply', sa.Text(), nullable=False),
    sa.Column('proposed_action', sa.String(length=50), nullable=True),
    sa.Column('reason_codes', sa.JSON(), nullable=False),
    sa.Column('verified_facts', sa.JSON(), nullable=False),
    sa.Column('policy_id', sa.String(length=50), nullable=True),
    sa.Column('trace', sa.JSON(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audits',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('run_id', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('actor', sa.String(length=80), nullable=False),
    sa.Column('before', sa.Text(), nullable=False),
    sa.Column('after', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipments',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('order_id', sa.String(length=40), nullable=False),
    sa.Column('carrier', sa.String(length=30), nullable=False),
    sa.Column('tracking_id', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('scan_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scan_city', sa.String(length=80), nullable=False),
    sa.Column('eta', sa.String(length=30), nullable=True),
    sa.Column('simulate_timeout', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipments')
    op.drop_table('audits')
    op.drop_table('runs')
    op.drop_table('reviews')
    op.drop_table('review_investigations')
    op.drop_table('tickets')
    op.drop_table('orders')
    op.drop_table('products')
    op.drop_table('vendors')
    op.drop_table('customers')
    # ### end Alembic commands ###
