"use client";
import { ResponsiveContainer, BarChart as Bars, Bar, AreaChart, Area, LineChart, Line, PieChart, Pie, Cell, XAxis, YAxis, CartesianGrid, Tooltip, Legend } from "recharts";
export const COLORS=["#6246ea","#a98af8","#10b981","#f5b544","#ef7284","#64a3ed"];
type Datum={label:string;value:number;color?:string};
type Series={key:string;label:string;color:string};
function Table({headers,rows}:{headers:string[];rows:(string|number)[][]}){return <details className="chart-data"><summary>View chart data</summary><div className="table-scroll"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table></div></details>}
export function BarChart({data,unit="",onSelect}:{data:Datum[];unit?:string;onSelect?:(label:string)=>void}){return <><div className="bar-chart">{data.map((d,i)=><button key={d.label} className="bar-chart-row" disabled={!onSelect} onClick={()=>onSelect?.(d.label)}><span>{d.label.replaceAll("_"," ")}</span><span className="bar-track"><span style={{width:`${100*d.value/Math.max(1,...data.map(x=>x.value))}%`,background:d.color||COLORS[i%COLORS.length]}}/></span><strong>{d.value.toLocaleString()}{unit}</strong></button>)}</div><Table headers={["Category",`Value ${unit}`]} rows={data.map(d=>[d.label,d.value])}/></>}
export function DonutChart({data,centerValue,centerLabel,onSelect}:{data:Datum[];centerValue?:string|number;centerLabel?:string;onSelect?:(label:string)=>void}){return <><div className="donut-wrap"><div className="donut-plot"><ResponsiveContainer width="100%" height={210}><PieChart><Pie data={data} dataKey="value" nameKey="label" innerRadius={66} outerRadius={91} paddingAngle={3} isAnimationActive={false} onClick={(_,index)=>onSelect?.(data[index].label)}>{data.map((d,i)=><Cell key={d.label} fill={d.color||COLORS[i%COLORS.length]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer><div className="donut-center"><strong>{centerValue}</strong><span>{centerLabel}</span></div></div><div className="chart-legend">{data.map((d,i)=><button disabled={!onSelect} onClick={()=>onSelect?.(d.label)} key={d.label}><i style={{background:d.color||COLORS[i%COLORS.length]}}/><span>{d.label.replaceAll("_"," ")}</span><strong>{d.value}</strong></button>)}</div></div><Table headers={["Category","Count"]} rows={data.map(d=>[d.label,d.value])}/></>}
export function SeriesChart({data,series,mode,percent=false,stacked=true}:{data:{label:string;[key:string]:number|string|null}[];series:Series[];mode:"area"|"line"|"columns";percent?:boolean;stacked?:boolean;onSelect?:(label:string)=>void}){const axis=<><CartesianGrid strokeDasharray="3 4" vertical={false} stroke="#eceaf6"/><XAxis dataKey="label" tick={{fontSize:10,fill:"#74809b"}} axisLine={false} tickLine={false} minTickGap={22}/><YAxis tick={{fontSize:10,fill:"#74809b"}} axisLine={false} tickLine={false} width={34} unit={percent?"%":undefined}/><Tooltip contentStyle={{borderRadius:10,borderColor:"#e7e3f5",fontSize:12}}/><Legend wrapperStyle={{fontSize:11,paddingTop:12}}/></>;return <><div className="series-chart"><ResponsiveContainer width="100%" height="100%">{mode==="area"?<AreaChart data={data}>{axis}{series.map(s=><Area key={s.key} type="monotone" dataKey={s.key} name={s.label} stroke={s.color} fill={s.color} fillOpacity={.2} stackId={stacked?"total":undefined} isAnimationActive={false}/>)}</AreaChart>:mode==="line"?<LineChart data={data}>{axis}{series.map(s=><Line key={s.key} type="monotone" dataKey={s.key} name={s.label} stroke={s.color} strokeWidth={2.5} dot={{r:3}} isAnimationActive={false}/>)}</LineChart>:<Bars data={data}>{axis}{series.map(s=><Bar key={s.key} dataKey={s.key} name={s.label} fill={s.color} stackId={stacked?"total":undefined} radius={[3,3,0,0]} maxBarSize={38} isAnimationActive={false}/>)}</Bars>}</ResponsiveContainer></div><Table headers={["Period / category",...series.map(s=>s.label)]} rows={data.map(d=>[d.label,...series.map(s=>d[s.key]??"Unavailable")])}/></>}
export function Heatmap({rows,columns,percent=false,onSelect}:{rows:{label:string;values:number[]}[];columns:string[];percent?:boolean;onSelect?:(row:string,column:string)=>void}){const max=Math.max(1,...rows.flatMap(r=>r.values));return <div className="heatmap table-scroll"><table><thead><tr><th>Category</th>{columns.map(c=><th key={c}>{c.replaceAll("_"," ")}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.label}><th>{r.label}</th>{r.values.map((v,i)=><td key={i}><button disabled={!onSelect} onClick={()=>onSelect?.(r.label,columns[i])} style={{background:`rgba(98,70,234,${.07+.8*v/max})`,color:v/max>.5?"white":"#342969"}} aria-label={`${r.label}, ${columns[i]}: ${v}${percent?"%":""}`}>{v}{percent?"%":""}</button></td>)}</tr>)}</tbody></table></div>}
export function DotPlot({data,unit="%",onSelect}:{data:Datum[];unit?:string;onSelect?:(label:string)=>void}){return <><div className="dot-plot">{data.map((d,i)=><div key={d.label}><button className="text-button" disabled={!onSelect} onClick={()=>onSelect?.(d.label)}>{d.label}</button><div><i style={{left:`${Math.min(100,d.value)}%`,background:COLORS[i%COLORS.length]}}/></div><strong>{d.value}{unit}</strong></div>)}</div><Table headers={["Vendor",`Completeness ${unit}`]} rows={data.map(d=>[d.label,d.value])}/></>}

