"use client";
import { Suspense, useCallback, useEffect, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { Search, ShieldCheck, Workflow, ArrowRight } from "lucide-react";
import { api, Meta, Run, Dashboard } from "@/lib/api";
import type { components } from "@/lib/openapi.generated";
import { Card, EmptyState, ErrorState, PageTitle, Pill, Stat, Tabs } from "@/components/ui";
import { BarChart, DonutChart, SeriesChart } from "@/components/charts";
import { Conversation, Evidence } from "@/components/cx/case-workspace";
import { TicketDetail, QueueTicket, AuditEntry, readable, decisionLabel } from "@/components/cx/types";
import "./cx.css";
export default function CXPage(){return <Suspense fallback={<div className="loading">Loading support workspace…</div>}><CXWorkspace/></Suspense>}
function CXWorkspace(){
 const router=useRouter(),params=useSearchParams();
 const view=params.get("view")||"inbox",selected=params.get("ticket")||"",intent=params.get("intent")||"",channel=params.get("channel")||"",search=params.get("q")||"";
 const [tickets,setTickets]=useState<QueueTicket[]>([]),[detail,setDetail]=useState<TicketDetail|null>(null),[meta,setMeta]=useState<Meta|null>(null),[charts,setCharts]=useState<Dashboard|null>(null);
 const [audit,setAudit]=useState<AuditEntry[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[editedReply,setEditedReply]=useState(""),[query,setQuery]=useState(search),[offset,setOffset]=useState(0),[total,setTotal]=useState(0),[node,setNode]=useState(0);
 const navigate=(values:Record<string,string>)=>{const next=new URLSearchParams(params.toString());Object.entries(values).forEach(([k,v])=>next.set(k,v));router.push(`/cx?${next}`)};
 const load=useCallback(async(id:string)=>{const result=await api<TicketDetail>(`/cx/tickets/${id}`);setDetail(result);setEditedReply(result.run?.proposed_reply||"");setAudit(result.run?(await api<{items:AuditEntry[]}>(`/cx/runs/${result.run.id}/audit`)).items:[]);},[]);
 const refreshCharts=useCallback(()=>api<Dashboard>("/dashboard").then(setCharts),[]);
 useEffect(()=>{api<Meta>("/meta").then(setMeta).catch(e=>setError(e.message));refreshCharts().catch(e=>setError(e.message));},[refreshCharts]);
 useEffect(()=>{let active=true;api<{items:QueueTicket[];total:number}>(`/cx/tickets?limit=50&offset=${offset}&q=${encodeURIComponent(search)}&intent=${encodeURIComponent(intent)}&channel=${encodeURIComponent(channel)}`).then(r=>{if(active){setTickets(r.items);setTotal(r.total)}}).catch(e=>setError(e.message));return()=>{active=false}},[offset,intent,channel,search]);
 useEffect(()=>{if(selected){setError("");setNode(0);setDetail(null);load(selected).catch(e=>setError(e.message));}},[selected,load]);
 async function run(){if(!selected)return;setBusy(true);setError("");try{await api<Run>(`/cx/tickets/${selected}/run`,{method:"POST"});await load(selected);await refreshCharts();}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function decide(action:"approve"|"edit"|"escalate"){if(!detail?.run)return;setBusy(true);setError("");try{const payload:components["schemas"]["DecisionInput"]={action,actor:"Demo Agent",edited_reply:action==="edit"?editedReply:undefined};await api(`/cx/runs/${detail.run.id}/decision`,{method:"POST",body:JSON.stringify(payload)});await load(selected);await refreshCharts();}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 useEffect(()=>{setQuery(search)},[search]);
 const panel=params.get("panel")||(selected?"conversation":"queue");
 const filtered=tickets;
 const trace=detail?.run?.trace||[],step=trace[node];
 return <div className="page-wrap"><PageTitle eyebrow="CUSTOMER EXPERIENCE / 02" title="CX Support" subtitle="From customer message to a verified answer. Every decision, visible." right={<Pill tone="good">Demo environment</Pill>}/><Tabs items={[{id:"inbox",label:"Live tickets"},{id:"human",label:"Human review",count:charts?.review_queue.length},{id:"workflow",label:"Workflow explorer"},{id:"analytics",label:"CX analytics"}]} value={view} onChange={v=>navigate({view:v})}/>{error&&<ErrorState message={error}/>}
 {view==="inbox"&&<><div className="cx-mobile-panels"><Tabs items={[{id:"queue",label:"Queue"},{id:"conversation",label:"Conversation"},{id:"evidence",label:"Evidence"}]} value={panel} onChange={v=>navigate({panel:v})}/></div><div className="cx-workspace" data-panel={panel}><Card className="cx-inbox"><div className="queue-header"><h2>Case queue <span>{total}</span></h2><form onSubmit={e=>{e.preventDefault();setOffset(0);navigate({q:query})}}><label className="search-box"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search all cases…" aria-label="Search all cases"/></label><button className="text-button" type="submit">Search cases</button></form><div className="cx-filter-row"><select aria-label="Synthetic intent filter" value={intent} onChange={e=>{setOffset(0);navigate({intent:e.target.value})}}><option value="">All demo intents</option>{["wismo","return","exchange","refund","cancellation","payment","product","unknown"].map(i=><option key={i} value={i}>{readable(i)}</option>)}</select><select aria-label="Channel filter" value={channel} onChange={e=>{setOffset(0);navigate({channel:e.target.value})}}><option value="">All channels</option><option value="FRESHDESK">Freshdesk</option><option value="GUPSHUP_WHATSAPP">WhatsApp</option></select></div><p>All synthetic cases · {offset+1}–{Math.min(offset+50,total)}</p></div><div className="cx-ticket-list">{filtered.map((t,i)=><button key={t.id} className={`queue-item ${selected===t.id?"selected":""}`} disabled={busy} onClick={()=>navigate({ticket:t.id,panel:"conversation"})}><div className="cx-ticket-title"><span className={`cx-avatar color-${i%4}`}>{t.customer_id.slice(-2)}</span><div><strong>{t.customer_name||t.id}</strong><small>{t.channel==="FRESHDESK"?"Freshdesk":"WhatsApp"} · {t.language}</small></div></div><p>{t.message}</p><small>{t.id}</small></button>)}{!filtered.length&&<EmptyState>No cases match these filters.</EmptyState>}</div><div className="cx-pagination"><button className="secondary-button" disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-50))}>Previous</button><button className="secondary-button" disabled={offset+50>=total} onClick={()=>setOffset(offset+50)}>Next</button></div></Card>{detail?<><Conversation detail={detail} meta={meta} busy={busy} editedReply={editedReply} setEditedReply={setEditedReply} onRun={run} onDecide={decide} onWorkflow={()=>navigate({view:"workflow"})} audit={audit}/><Evidence detail={detail} meta={meta}/></>:<Card className="cx-welcome"><ShieldCheck size={35}/><h2>Support grounded in evidence</h2><p>Select a customer case to inspect the message, investigate its facts, and review the next step.</p><Pill tone="blue">All actions are simulated</Pill></Card>}</div></>}
 {view==="human"&&<><div className="stats-grid three"><Stat label="NEEDS HUMAN REVIEW" value={charts?.review_queue.length||0} detail="Latest result per case in this session"/><Stat label="CASES PROCESSED" value={charts?.processed||0} detail="Current browser session"/><Stat label="LIVE WRITES" value="0" detail="Only mock adapters are enabled" tone="good-stat"/></div><Card title="Human review queue" subtitle="Inspect evidence before taking action">{charts?.review_queue.length?<div className="human-review-list">{charts.review_queue.map(r=><button key={r.ticket_id} onClick={()=>navigate({view:"inbox",ticket:r.ticket_id})}><span className="cx-avatar">{r.ticket_id.slice(-2)}</span><div><strong>{r.ticket_id} · {readable(r.intent)}</strong><p>{r.reasons.length?r.reasons.map(readable).join(" · "):"Eligible proposal awaiting a human decision"}</p></div><Pill tone={r.decision==="approval_required"?"warn":"bad"}>{decisionLabel(r.decision)}</Pill><ArrowRight size={16}/></button>)}</div>:<EmptyState>No cases awaiting review in this session. Run a return, cancellation, or deliberate failure from Live tickets.</EmptyState>}</Card></>}
 {view==="workflow"&&<><div className="notice"><Workflow size={18}/><div>Execution trace for {selected||"the selected case"}. Steps reflect actual execution; no model metrics are simulated.</div></div>{!trace.length?<Card><EmptyState>Select and run a case in Live tickets to inspect its workflow.</EmptyState></Card>:<div className="chart-grid equal"><Card title="Execution path" subtitle="Select a step to inspect the recorded result"><div className="workflow-nodes">{trace.map((t,i)=><button className={node===i?"selected":""} key={i} onClick={()=>setNode(i)}><span>{i+1}</span><div><strong>{readable(String(t.stage||t.role||"model call"))}</strong><small>{String(t.kind||t.model||"Deterministic code")}</small></div><Pill tone={t.result==="blocked"?"bad":"blue"}>{String(t.result||t.status||"recorded")}</Pill></button>)}</div></Card><Card title="Step evidence" subtitle="Raw trace from this case"><pre className="trace-json">{JSON.stringify(step,null,2)}</pre><button className="secondary-button" onClick={()=>navigate({view:"inbox"})}>Back to case</button></Card></div>}</>}
 {view==="analytics"&&<><div className="stats-grid three"><Stat label="CASES IN DATASET" value={total} detail="Synthetic seed records"/><Stat label="PROCESSED THIS SESSION" value={charts?.processed||0} detail="Distinct cases; latest run only"/><Stat label="MODEL CONFIDENCE" value={charts?.confidence_count||"—"} detail="Measured classifier confidence samples"/></div><div className="chart-grid equal"><Card title="Language distribution" subtitle="All seeded customer cases">{charts&&<BarChart data={charts.languages}/>}</Card><Card title="Agent outcomes" subtitle="Current browser session · latest result per case">{charts?.outcomes.length?<DonutChart data={charts.outcomes} centerValue={charts.processed} centerLabel="processed cases"/>:<EmptyState>Run a case to populate measured outcomes.</EmptyState>}</Card></div><div className="chart-grid equal"><Card title="Classifier confidence" subtitle="Model-classified cases only; deterministic rules excluded">{charts?.confidence_count?<SeriesChart data={charts.confidence} mode="columns" stacked={false} series={[{key:"count",label:"Cases",color:"#9c77ef"}]}/>:<EmptyState>No live classifier confidence samples in this session.</EmptyState>}</Card><Card title="Model measurement boundary"><p className="muted">{meta?.model_mode}. Confidence, token usage and model latency must come from live execution traces. The deterministic demo does not create substitute measurements.</p></Card></div></>}
 </div>
}
