"use client";
import { Suspense, useEffect, useState } from "react";
import { MessageSquareText, Search } from "lucide-react";
import { api, Dashboard } from "@/lib/api";
import { Card, EmptyState, ErrorState, PageTitle, Pill, Stat, Tabs } from "@/components/ui";

import { BarChart, Heatmap, SeriesChart } from "@/components/charts";

import { useWorkspaceUrl } from "@/lib/use-workspace-url";

type ReviewRow = { product_id: string; sku: string; name: string; category: string; review_count: number; negative_count: number; top_issue: string | null; issue_count: number; alert: boolean };
type ReviewOverview = { demo: boolean; total_reviews: number; products: ReviewRow[] };
type Evidence = { id: string; rating: number; text: string; date: string; analysis: { issues: string[]; sentiment: string } };
type Detail = { product: { id: string; name: string; sku: string; vendor_id: string }; evidence: Evidence[] };
type Investigation = { id: string; product_id: string; issue_code: string; status: string; owner: string; notes: string };

export default function ReviewsPage(){return <Suspense fallback={<div className="loading">Loading reviews…</div>}><ReviewWorkspace/></Suspense>}
function ReviewWorkspace() {
 const {params,change}=useWorkspaceUrl();const view=params.get("view")||"signals",category=params.get("category")||"",issue=params.get("issue")||"",product=params.get("product")||"";
 const [issueChoice,setIssueChoice]=useState("sizing"),[busy,setBusy]=useState(false),[note,setNote]=useState("");
  const [charts,setCharts] = useState<Dashboard|null>(null);
  const [data, setData] = useState<ReviewOverview | null>(null);
  const [detail, setDetail] = useState<Detail | null>(null);
  const [query, setQuery] = useState("");
  const [investigations, setInvestigations] = useState<Investigation[]>([]);
  const [error, setError] = useState("");
  useEffect(()=>{api<Dashboard>(`/dashboard?category=${encodeURIComponent(category)}&issue=${encodeURIComponent(issue)}`).then(setCharts).catch(e=>setError(e.message));},[category,issue]);
  useEffect(() => { api<ReviewOverview>(`/reviews/overview?category=${encodeURIComponent(category)}&issue=${encodeURIComponent(issue)}`).then(setData).catch(e => setError(e.message)); }, [category,issue]);
  useEffect(() => { api<{items: Investigation[]}>("/reviews/investigations").then(x => setInvestigations(x.items)).catch(() => {}); }, []);
  useEffect(()=>{setDetail(null);if(product)api<Detail>(`/reviews/products/${product}?issue=${encodeURIComponent(issue)}`).then(setDetail).catch(e=>setError(e.message));},[product,issue]);
  useEffect(()=>{if(detail)setIssueChoice(issue||detail.evidence.flatMap(r=>r.analysis.issues)[0]||"other")},[detail,issue]);
  async function select(id:string){change({product:id});}
  async function updateInvestigation(id:string,status:string,notes:string){setBusy(true);try{await api(`/reviews/investigations/${id}`,{method:"PATCH",body:JSON.stringify({status,notes})});setInvestigations((await api<{items:Investigation[]}>("/reviews/investigations")).items);}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  async function investigate() { if (!detail) return; const issue = issueChoice; setBusy(true); try { await api("/reviews/investigations", { method: "POST", body: JSON.stringify({ product_id: detail.product.id, issue_code: issue, owner: "Demo Category Team", notes: "Review customer evidence and product specification." }) }); setInvestigations((await api<{items: Investigation[]}>("/reviews/investigations")).items);setNote("Investigation opened. Review it in the Investigations tab."); } catch (e) { setError((e as Error).message); } finally{setBusy(false)} }
  async function analyze(id: string) { try { await api(`/reviews/${id}/analyze`, { method: "POST" }); if (detail) setDetail(await api<Detail>(`/reviews/products/${detail.product.id}?issue=${encodeURIComponent(issue)}`));setCharts(await api<Dashboard>(`/dashboard?category=${encodeURIComponent(category)}&issue=${encodeURIComponent(issue)}`)); } catch (e) { setError(`Model extraction: ${(e as Error).message}`); } }
  const products = data?.products.filter(p => `${p.name} ${p.sku} ${p.category}`.toLowerCase().includes(query.toLowerCase())) || [];
  return <div className="page-wrap"><PageTitle eyebrow="VOICE OF CUSTOMER / 03" title="Review Intelligence" subtitle="See recurring product-quality signals and the customer words behind them." right={<Pill tone="blue">Synthetic review analysis</Pill>} />
    <Tabs items={[{id:"signals",label:"Product signals"},{id:"investigations",label:"Investigations",count:investigations.length}]} value={view} onChange={v=>change({view:v})}/><div className="filter-bar"><label>Category <select value={category} onChange={e=>change({category:e.target.value,product:""})}><option value="">All categories</option>{charts?.review_heatmap.rows.map(r=><option key={r.label}>{r.label}</option>)}</select></label><label>Issue <select value={issue} onChange={e=>change({issue:e.target.value,product:""})}><option value="">All issues</option>{["sizing","colour_mismatch","fabric_quality","shrinkage","stitching","appearance_mismatch","value","other"].map(i=><option value={i} key={i}>{i.replaceAll("_"," ")}</option>)}</select></label><button className="text-button" onClick={()=>change({category:"",issue:"",product:""})}>Clear filters</button><span>Charts: selected category · table: products with selected issue</span></div>
    <div className="notice"><MessageSquareText size={19} /><div><strong>Evidence first.</strong> Counts and issue tags are computed from seeded reviews. These are demo signals for investigation, not conclusions about real Dhaga products or vendors.</div></div>
    {error && <ErrorState message={error} />}{!data ? <div className="loading">Loading reviews…</div> : <><div className="stats-grid three"><Stat label="REVIEWS INGESTED" value={data.total_reviews} detail="Synthetic dataset" /><Stat label="PRODUCTS MAPPED" value={data.products.length} detail="Products matching active filters" /><Stat label="INVESTIGATION FLAGS" value={data.products.filter(p => p.alert).length} detail="Volume and negative-rate rule" /></div>
      {view==="signals" && <>{charts && <><div className="chart-grid equal"><Card title={issue?`${issue.replaceAll("_"," ")} prevalence`:"Review volume over time"} subtitle={issue?"% of reviews mentioning issue · fewer than 5 reviews suppressed":"Weekly buckets · seeded review dates"}><SeriesChart data={charts.review_trend} mode="line" percent={!!issue} series={issue?[{key:"prevalence",label:"Issue prevalence",color:"#6246ea"}]:[{key:"reviews",label:"All reviews",color:"#6246ea"},{key:"negative",label:"1–2 star reviews",color:"#f08094"}]}/></Card><Card title="Customer sentiment by category" subtitle="Seeded analysis; live extraction may update tags"><SeriesChart data={charts.review_sentiment.filter(r=>!category||r.label===category)} mode="columns" stacked={false} series={[{key:"positive",label:"Positive",color:"#10b981"},{key:"negative",label:"Negative",color:"#ef7284"},{key:"mixed",label:"Mixed",color:"#a98af8"},{key:"unknown",label:"Unknown",color:"#a6adbf"}]}/></Card></div><div className="chart-grid equal"><Card title="Issue concentration" subtitle="Distinct reviews per issue · multiple issues may coexist"><Heatmap rows={charts.review_heatmap.rows.filter(r=>!category||r.label===category)} columns={charts.review_heatmap.columns} onSelect={(row,col)=>change({category:row,issue:col,product:""})}/></Card><Card title="Most mentioned issues" subtitle="Distinct review counts"><BarChart data={charts.review_issues.slice(0,6)} onSelect={label=>change({issue:label,product:""})}/></Card></div></>}
      <div className="review-grid"><Card className="table-card"><div className="table-toolbar"><div><h2>Product signals</h2><p>Open a product to inspect supporting reviews. Alert rule: at least five reviews in both 30-day periods and a rising negative rate.</p></div><label className="search-box"><Search size={16} /><input aria-label="Search products" value={query} onChange={e => setQuery(e.target.value)} placeholder="Search product or SKU" /></label></div>
        <div className="table-scroll"><table><thead><tr><th>PRODUCT</th><th>REVIEWS</th><th>NEGATIVE</th><th>TOP ISSUE</th><th>STATUS</th></tr></thead><tbody>{products.map(p => <tr tabIndex={0} onKeyDown={e=>{if(e.key==="Enter")select(p.product_id)}} onClick={() => select(p.product_id)} key={p.product_id} className={detail?.product.id === p.product_id ? "active-row" : ""}><td><strong>{p.name}</strong><small>{p.sku} · {p.category}</small></td><td>{p.review_count}</td><td>{p.negative_count}</td><td>{p.top_issue?.replaceAll("_", " ") || "—"}</td><td><Pill tone={p.alert ? "warn" : "neutral"}>{p.alert ? "Investigate" : "Monitor"}</Pill></td></tr>)}</tbody></table></div></Card>
        <Card title={detail ? detail.product.name : "Review evidence"} subtitle={detail ? `${detail.product.sku} · ${detail.product.vendor_id}` : "Select a product"} className="evidence-card">{!detail ? <EmptyState>Select a product to see its review evidence.</EmptyState> : <><div className="action-row"><select aria-label="Investigation issue" value={issueChoice} onChange={e=>setIssueChoice(e.target.value)}>{["sizing","colour_mismatch","fabric_quality","shrinkage","stitching","appearance_mismatch","value","other"].map(i=><option key={i} value={i}>{i.replaceAll("_"," ")}</option>)}</select><button className="primary-button" disabled={busy} onClick={investigate}>Open investigation</button></div>{note&&<p className="success-note">{note}</p>}<div className="evidence-list">{detail.evidence.map(r => <div className="evidence-item" key={r.id}><div><span className="stars">{"★".repeat(r.rating)}{"☆".repeat(5 - r.rating)}</span><small>{r.date}</small></div><p>“{r.text}”</p><div className="tag-row">{r.analysis?.issues?.map(issue => <Pill key={issue} tone="warn">{issue.replaceAll("_", " ")}</Pill>)}</div><button className="text-button" onClick={() => analyze(r.id)}>Re-analyze with live model</button></div>)}</div></>}</Card></div>
      </>}{view==="investigations" && <div className="section-spaced"><Card title="Investigation queue" subtitle="Human decisions, not vendor verdicts">{investigations.length ? investigations.map(item => <div className="context-row" key={item.id}><div><span>{item.product_id} · {item.issue_code.replaceAll("_", " ")}</span><small>{item.owner} · {item.id}</small></div><div className="investigation-actions"><input disabled={busy} aria-label={`Notes ${item.id}`} value={item.notes} onChange={e=>setInvestigations(rows=>rows.map(r=>r.id===item.id?{...r,notes:e.target.value}:r))}/><button className="secondary-button" disabled={busy} onClick={()=>updateInvestigation(item.id,item.status,item.notes)}>Save notes</button><select aria-label={`Status ${item.id}`} value={item.status} disabled={busy} onChange={e=>updateInvestigation(item.id,e.target.value,item.notes)}>{["open","investigating","resolved","dismissed"].map(v=><option key={v}>{v}</option>)}</select><button className="text-button" onClick={()=>change({view:"signals",product:item.product_id,issue:item.issue_code})}>View evidence</button></div></div>) : <EmptyState>No investigations opened yet.</EmptyState>}</Card></div>}
    </>}
  </div>;
}
