"use client";
import { useEffect, useState } from "react";
import { PackageCheck, Search } from "lucide-react";
import { api, Product } from "@/lib/api";
import { Card, EmptyState, ErrorState, PageTitle, Pill, Stat } from "@/components/ui";

type Overview = { demo: boolean; total: number; states: Record<string, number>; blockers: Record<string, number>; drops: { date: string; states: Record<string, number> }[]; products: Product[] };
const statusTone = (status: string) => status === "ready" ? "good" : status === "blocked" ? "bad" : "warn";

export default function CatalogPage() {
  const [data, setData] = useState<Overview | null>(null);
  const [selected, setSelected] = useState<Product | null>(null);
  const [query, setQuery] = useState("");
  const [error, setError] = useState("");
  const [actionNote, setActionNote] = useState("");
  const [colour, setColour] = useState("");
  const [fabric, setFabric] = useState("");
  const [intakeCSV, setIntakeCSV] = useState("sku,vendor_id,name,category,colour,fabric,price\nDHG-90001,VEN01,Demo Dress,Dresses,Dark Wine,Cotton,899");
  const [intakeResult, setIntakeResult] = useState<{accepted:number; rejected:number; rows:{line:number;sku:string;errors:string[]}[]} | null>(null);
  useEffect(() => { api<Overview>("/catalog/overview").then(setData).catch(e => setError(e.message)); }, []);
  async function refresh(id: string) { const [overview, product] = await Promise.all([api<Overview>("/catalog/overview"), api<Product>(`/catalog/products/${id}`)]); setData(overview); setSelected(product); }
  async function act(name: "normalize" | "qa" | "generate-copy" | "approve") { if (!selected) return; setError(""); setActionNote(""); try { const result = await api<Record<string, unknown>>(`/catalog/products/${selected.id}/${name}`, {method:"POST", body: name === "approve" ? JSON.stringify({actor:"Demo Listing Lead"}) : undefined}); await refresh(selected.id); setActionNote(name === "approve" ? "Publish-ready payload approved for export. Nothing was published." : `${name.replaceAll("-", " ")} completed. ${result.suggestion ? `Suggested colour: ${result.suggestion}.` : ""}`); } catch(e) { setError((e as Error).message); } }
  async function saveEdit() { if (!selected) return; setError(""); try { await api<Product>(`/catalog/products/${selected.id}`, {method:"PATCH",body:JSON.stringify({actor:"Demo Listing Lead",colour:colour || undefined,fabric:fabric || undefined})}); await refresh(selected.id); setActionNote("Human correction saved with provenance."); setColour(""); setFabric(""); } catch(e) { setError((e as Error).message); } }
  async function previewIntake() { setError(""); try { setIntakeResult(await api("/catalog/intake/preview", {method:"POST",body:JSON.stringify({csv_text:intakeCSV})})); } catch(e) { setError((e as Error).message); } }
  async function applyIntake() { setError(""); try { const result = await api<{count:number}>("/catalog/intake/apply",{method:"POST",body:JSON.stringify({csv_text:intakeCSV})}); setActionNote(`${result.count} synthetic draft(s) added. Nothing published.`); setData(await api<Overview>("/catalog/overview")); setIntakeResult(null); } catch(e) { setError((e as Error).message); } }
  const products = data?.products.filter(p => `${p.name} ${p.sku} ${p.vendor_id}`.toLowerCase().includes(query.toLowerCase())) || [];
  return <div className="page-wrap"><PageTitle eyebrow="LISTING OPERATIONS / 04" title="Catalog Velocity Engine" subtitle="Move product drafts through evidence, exception review, and drop readiness." right={<Pill tone="blue">Synthetic 50-SKU batch</Pill>} />
    <div className="notice"><PackageCheck size={19} /><div><strong>Operations preview.</strong> Readiness is calculated from seeded field and image blockers. Unknown catalog facts are left missing, and no product is published from this demo.</div></div>
    {error ? <ErrorState message={error} /> : !data ? <div className="loading">Loading catalog…</div> : <><div className="stats-grid"><Stat label="PRODUCT DRAFTS" value={data.total} detail="Across five demo vendors" /><Stat label="READY" value={data.states.ready || 0} detail="No current blockers" tone="good-stat" /><Stat label="NEEDS REVIEW" value={data.states.needs_review || 0} detail="Resolve source conflict" /><Stat label="BLOCKED" value={data.states.blocked || 0} detail="Missing critical input" tone="bad-stat" /></div>
      <div className="two-col"><Card title="Drop readiness" subtitle="Illustrative Tuesday and Friday drops"><div className="drop-grid">{data.drops.map(d => <div className="drop-card" key={d.date}><strong>{d.date}</strong><div><span className="drop-ready" /> {d.states.ready || 0} ready</div><div><span className="drop-blocked" /> {d.states.blocked || 0} blocked</div><small>{d.states.needs_review || 0} need review</small></div>)}</div></Card><Card title="Top blockers" subtitle="Deterministic checks"><div className="blocker-list">{Object.entries(data.blockers).sort((a,b) => b[1]-a[1]).map(([name, count]) => <div key={name}><span>{name.replaceAll("_", " ")}</span><strong>{count}</strong></div>)}</div></Card></div>
      <div className="catalog-grid"><Card className="table-card"><div className="table-toolbar"><div><h2>Product pipeline</h2><p>Inspect source values and readiness blockers.</p></div><label className="search-box"><Search size={16} /><input aria-label="Search catalog" value={query} onChange={e => setQuery(e.target.value)} placeholder="Search SKU or vendor" /></label></div><div className="table-scroll"><table><thead><tr><th>PRODUCT</th><th>VENDOR</th><th>DROP</th><th>STATUS</th></tr></thead><tbody>{products.map(p => <tr onClick={() => setSelected(p)} key={p.id} className={selected?.id === p.id ? "active-row" : ""}><td><strong>{p.name}</strong><small>{p.sku} · {p.category}</small></td><td>{p.vendor_id}</td><td>{p.target_drop}</td><td><Pill tone={statusTone(p.status)}>{p.status.replaceAll("_", " ")}</Pill></td></tr>)}</tbody></table></div></Card>
        <Card title={selected ? selected.name : "Product detail"} subtitle={selected ? `${selected.sku} · ${selected.vendor_id}` : "Select a draft"} className="detail-card">{!selected ? <EmptyState>Select a product to inspect its source data.</EmptyState> : <><div className="detail-status"><Pill tone={statusTone(selected.status)}>{selected.status.replaceAll("_", " ")}</Pill><span>Target drop {selected.target_drop}</span></div>{selected.images[0] ? <div className="catalog-image"><img src={selected.images[0]} alt={`Synthetic illustration for ${selected.name}`} /></div> : <div className="catalog-image missing">No image supplied by demo vendor</div>}<h3>Readiness blockers</h3>{selected.workflow.blockers.length ? <div className="tag-row">{selected.workflow.blockers.map(b => <Pill key={b} tone="bad">{b.replaceAll("_", " ")}</Pill>)}</div> : <p className="muted">No deterministic blockers.</p>}<h3>Raw vendor input</h3><div className="facts-grid">{Object.entries(selected.raw_attributes).filter(([k])=>k!=="generated_copy").map(([k,v]) => <div key={k}><span>{k.replaceAll("_", " ")}</span><strong>{String(v ?? "Missing")}</strong></div>)}</div><h3>Canonical listing record</h3><div className="facts-grid"><div><span>Colour</span><strong>{selected.colour || "Missing"}</strong></div><div><span>Fabric</span><strong>{selected.fabric || "Missing"}</strong></div><div><span>Price</span><strong>₹{selected.price}</strong></div></div><div className="policy-box"><span>DATA PROVENANCE</span><pre>{JSON.stringify(selected.field_provenance, null, 2)}</pre></div><h3>Listing team actions</h3><div className="action-row"><button className="secondary-button" onClick={()=>act("normalize")}>Normalize colour</button><button className="secondary-button" onClick={()=>act("qa")}>Run QA</button><button className="secondary-button" onClick={()=>act("generate-copy")}>Generate guarded copy</button><button className="primary-button" onClick={()=>act("approve")}>Approve export</button></div><div className="edit-grid"><input aria-label="Correct colour" placeholder="Correct colour" value={colour} onChange={e=>setColour(e.target.value)} /><input aria-label="Correct fabric" placeholder="Correct fabric" value={fabric} onChange={e=>setFabric(e.target.value)} /><button className="secondary-button" onClick={saveEdit}>Save correction</button></div>{actionNote && <p className="success-note">{actionNote}</p>}{selected.raw_attributes.generated_copy && <div className="policy-box"><span>GENERATED COPY · REQUIRES HUMAN APPROVAL</span><pre>{JSON.stringify(selected.raw_attributes.generated_copy, null, 2)}</pre></div>}</>}</Card></div>
      <div className="section-spaced"><Card title="Vendor intake" subtitle="CSV row validation and synthetic draft creation"><p className="muted">Required columns: sku, vendor_id, name, category, colour, fabric, price. Validation is atomic; rejected rows are never imported.</p><textarea className="intake-textarea" aria-label="Vendor CSV" value={intakeCSV} onChange={e=>setIntakeCSV(e.target.value)} /><div className="action-row"><button className="primary-button" onClick={previewIntake}>Validate rows</button>{intakeResult?.accepted && !intakeResult.rejected ? <button className="secondary-button" onClick={applyIntake}>Create demo drafts</button> : null}</div>{intakeResult && <div className="intake-results"><strong>{intakeResult.accepted} accepted · {intakeResult.rejected} rejected</strong>{intakeResult.rows.map(row=><div key={row.line}>Line {row.line} · {row.sku}: {row.errors.length ? row.errors.join(", ") : "valid"}</div>)}</div>}</Card></div>
    </>}
  </div>;
}
